name: Deploy to S3
run-name: ${{ github.actor }} started deploying code to S3
on:
  pull_request:
    types: closed
    branches:
      - 'main'
jobs:
  deploy-app:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Zip files
        run: git archive --format=zip --output ./app.zip main
      - name: List files
        run: ls
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Sync zip to S3
        run: aws s3 cp app.zip s3://acebook-of-troy
      - name: Deploy using AWS CodeDeploy
        run: aws deploy create-deployment --application-name ${{ env.codedeployname }}-${{ env.environment }} --deployment-group-name ${{ env.codedeployname }}-${{ env.environment }} --deployment-config-name CodeDeployDefault.OneAtATime --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
